// JavaScript Document
var atracciones = [
	"Miniatur Wunderland",
	"Europa-Park",
	"Neuschwanstein Schloss",
	"Insel Mainau",
	"Rothenburg ob der Tauber",
	"Phantasialand",
	"Tierpark Hellabrunn",
	"Nationalpark Schwarzwald",
	"Brandenburger Tor und Berliner Mauer",
	"Zugspitze",
	"Partnachklamm",
	"Schokoladenmarkt ChocolArt",
	"Ozeaneum Stralsund",
	"LEGOLAND Deutschland Resort",
	"Der Kölner Dom",
	"Der Marienplatz",
	"Burg Eltz",
	"Fernsehturm und Alexanderplatz",
	"Der Dresdner Zwinger",
	"Der Hamburger Hafen",
	"Reichsburg Cochem",
	"Ferienzentrum Schloss Dankern",
	"Volkswagen Autostadt",
	"Moseltal",
]