// JavaScript Document
var palabra = [
	"Er frühstückt morgens nicht",
	"Ich stehe auf",
	"Er raucht nicht",
	"Ich höre das Kind",
	"Das Kind faulenzt",
	"Der Hund tanzt nicht",
	"Der Stuhl ist groß",
	"Der Mann räumt das Haus auf",
	"Sie feiern abends",
	"Wir schwimmen nicht",
	"Du nimmst die Kamera",
	"Die Frau tanzt",
	"Sie schwimmt mittags",
	"Du isst ein Eis",
	"Wir lesen ein Buch",
	"Du siehst morgens fern",
	"Sie duscht nicht",
	"Ich zeichne ein Haus",
	"Die Katze schläft",
	"Ich esse Pizza",
	"Du malst den Tisch",
	"Ich tanze abends",
	"Das Kind sieht fern",
	"Er fotografiert einen Hund",
	"Ich nehme das Buch",
	"Er kauft ein Bier",
	"Ich habe kein Geld",
	"Der Hund trinkt Wasser",
	"Wir laufen morgens",
	"Der Hamburger ist lecker",
]