// JavaScript Document
//Para hacer carta
var palabras = [
	[//personas
		"r, Ingenieur",
		"r, Architekt",
		"r, Student",
		"e, Hausfrau",
		"r, Koch",
		"r, Arzt",
		"r, Mechaniker",
		"r, Lehrer",
		"r, Vater",
		"e, Mutter",
		"r, Sohn",
		"e, Tochter",
		"e, Groβeltern",
		"e, Eltern",
		"e, Kinder",
		"r, Hund",
		"e, Katze",
		"r, Papagei",
		"s, Kaninchen",
	],[//comida
		"r, Apfel",
		"e, Ananas",
		"e, Orange",
		"e, Birne",
		"e, Karotte",
		"r, Salat",
		"e, Zitrone",
		"r, Hamburger",
		"r, Käse",
		"r, Kuchen",
		"r, Fisch",
		"e, Suppe",
		"s, Ei",
		"s, Hähnchen",
		"s, Fleisch",
		"e, Kaffee",
		"s, Wasser",
		"s, Bier",
		"r, Saft",
		"e, Milch"
	],[//objetos casa
		"r, Kühlschrank",
		"e, Mikrowelle",
		"s, Buch",
		"r, Spiegel",
		"r, Stuhl",
		"r, Tisch",
		"e, Lampe",
		"s, Regal",
		"r, Schrank",
		"s, Radio",
		"s, Sofa",
		"s, Handy",
		"s, Auto"
	],[//verbos
		"schwimmen",
		"finden",
		"zeichnen",
		"sehen",
		"schlafen",
		"spielen",
		"kochen",
		"tanzen",
		"schlafen",
		"haben",
		"kaufen",
		"verkaufen",
		"arbeiten",
		"hören",
		"lesen",
		"besuchen",

		"können",
		"dürfen",
		"wollen",
		"möchten",
		
		"anrufen",
		"aufräumen",
		"anfangen",
		"aufstehen",
	],[//adjetivos
		"groβ",
		"klein",
		"alt",
		"neu",
		"teuer",
		"billig",
		"bequem",
		"schmutzig",
		"süβ",
		"salzig",
		"lang",
		"kurz",
		"lecker",
		"laut",
		"schön",
		"hell",
		"dunkel",
		"schön",
		"breit",
		"schmal",
		"kaputt"
	]
]