// JavaScript Document
//Para adivinar la palabra
var palabras = [
	[//profesiones
		"Chemiker -in",
		"Koch -in",
		"Arzt | Ärztin",
		"Lehrer -in",
		//"Landwirt -in",
		"Sänger -in",
		"Fotograf -in",
		/*"Friseur  -in",
		"Kellner -in",*/
		"Tänzer -in",
	],[//personas y animales
		"r, Mann",
		"e, Frau",
		"s, Kind",
		"r, Hund",
		"r, Papagei",
		"e, Katze",
		"e, Schildkröte",
		"e, Maus",
		"s, Haus",
		"e, Straβe"
	],[//cosas casa
		"r, Elektroherd",
		"r, Tisch",
		"r, Topf",
		"r, Kugelschreiber",
		"r, Stuhl",
		"r, Stecker",
		"r, Taschenrechner",
		"r, Wasserhahn",
		"r, Schrank",
		"e, Lampe",
		"e, Taschenlampe",
		"e, Glühbirne",
		"e, Steckdose",
		"e, Kamera",
		"e, Batterie",
		"s, Foto",
		"s, Radio",
		"s, Handy",
		"s, Telefon",
		"s, Regal",
		"r, Fernsehapparat",
		"r, Abfalleimer",
/*		"r, Geschirrspüler",*/
		"r, Kühlschrank",
		"e, Uhr",
/*		"e, Spüle",*/
		"e, Mikrowelle",
		"e, Waschmaschine",
/*		"e, Spülmaschine",*/
		"s, Bild",
		"s, Bett",
		"s, Auto",
		"s, Buch",
		"s, Klavier"
	],[//comida
		"s, Obst",
		"r, Apfel",
		"e, Ananas",
		"e, Banane",
		"e, Birne",
		"e, Erdbeere",
		"e, Orange",
		"e, Zitrone",
		"e, Avocado",
		"e, Tomate",
		"e, Weintraube | Traube",
/*		"r, Salat",*/
		"r, Kopfsalat",
		"e, Gurke",
		"e, Zwiebel",
		"e, Karotte",
		"e, Kartoffel",
		"e, Bohne",
		"r, Hamburger",
		"r, Fisch",
		"r, Käse",
		"r, Reis",
		"r, Kuchen",
		"r, Schinken",
		"e, Wurst",
		"e, Pommes frites",
		"e, Pizza",
		"e, Suppe",
		"e, Schokolade",
		"s, Hähnchen",
		"s, Fleisch",
		"s, Ei",
		"s, Schwein",
		"s, Brot",
		"s, Kotelett",
		"s, Eis",
		"r, Saft",
		"r, Tee",
		"r, Kaffee",
		"e, Milch",
		"e, Cola",
		"s, Bier",
		"s, Wasser",
	],[//utensilios
		"r, Löffel",
		"r, Teller",
		"r, Mundtuch",
		"e, Gabel",
		"e, Flasche",
		"e, Dose",
		"e, Tasse",
		"s, Messer",
		"s, Glas",
		"s, Menu / e, Speisekarte",
	],[//cosas casa 2
		"r, Sessel",
		"r, Spiegel",
		"r, Vorhang",
		"r, Teppich",
		"r, Schreibtisch",
		"r, Computer",
		"e, Couch",
		"e, Stehlampe",
		"e, Toilette",
		"e, Dusche",
		"e, Badewanne",
		"s, Fenster",
	]/*,[//cosas casa 2
		"s, Geld",
		"e, Sonne",
		"r, Mond",
		"r, Stern",
		"e, Blume",
	],[//partes del cuerpo
		"r, Kopf",
		"r, Zahn",
		"r, Mund",
		"r, Ellbogen",
		"r, Finger",
		"r, Fuβ",
		"e, Nase",
		"e, Hand",
		"s, Auge",
		"s, Haar",
		"s, Ohr",
	]*/
];

function getPalabra(maxi){
	if(maxi < 1) maxi = 1;
	if(maxi > palabras.length) maxi = palabras.length;
	var i = Math.floor(Math.random() * maxi);
	var j = Math.floor(Math.random() * palabras[i].length);
	return palabras[i][j];
}